<?php
$t = array(
		"index" 		=> "",
		"products" 		=> "Productos",
		"update" 		=> "Actualizar",
		"featured" 		=> "Productos Destacados",
		"product" 		=> "Producto",
		"pt" 		=> "Tabla de Precios",
		"price" 		=> "Precio",
		"prices" 		=> "Precios",
		"mexican-peso"	=> "Peso Mexicano",
		"american-dll"	=> "Dolar Americano",		
		"add-product" 	=> "Agregar Producto",
		"continue-editing" 	=> "Continuar Editando",
		"image" 		=> "Imagen",
		"other" 		=> " otro ",
		"othera" 		=> " otra ",
		"change" 		=> "Cambiar",
		"cancel" 		=> "Cancelar",
		"exit" 		=> "Salir",
		"related" 		=> "Productos Relacionados",
		"psws-no-match"		=> "Las contrase&ntilde;as introducidas no coinciden.",
		"slug"		=> "Link Permanente",
		"organize-categories"	=> "Organizar Categor&iacute;as",
		"organize-attributes"	=> "Organizar Atributos",
		"add-category-image"	=> "Agregar Imagen",
		
		"mkt" 		=> "Promos del Mes",
		"mistakes"	=> "Inconsistencias",
		"campaign"	=> "Campa&ntilde;a",
		
		"cash" 	=> "Efectivo",
		"card" 	=> "Tarjeta Bancaria",
		"wtra" 	=> "Transferencia",
		"chck" 	=> "Cheque",
		"bdep" 	=> "Dep&oacute;sito Bancario",
		
		"carrito"	=> "Carrito",
		"registrarse"	=> "Registrarse",
		"cuenta"	=> "Mi Cuenta",
		"pedidos"	=> "Pedidos",
		
		"stock" => "Stock",
		"tools" => "Herramientas",
		"sitemap" 	=> "Sitemap",
		"notifications"	=> "Notificaciones",
		
		"brand" 		=> "Marca",
		"brands" 		=> "Marcas",
		"edit-brand" 	=> "Editar Marca",
		"add-brand" 	=> "Agregar Marca",
		"website" 		=> "Sitio Web",
		"history" 		=> "Historial",		
		
		"no-cats"		=> "No se encontraron Categor&iacute;as",
		"no-files"		=> "No se encontraron Archivos",
		"no-results" 	=> "Sin Resultados",
		"success" 		=> "Listo!",
		"options" 		=> "Opciones",
		"user-exists" 	=> "El nombre de usuario elegido ya existe",
		"pwd-chars" => "La contrase&ntilde;a deber&iacute;a tener al menos 5 caracteres.",
		"list" 			=> "Lista de",
		"edited-ok"		=> " fue editado/a exitosamente!.",
		"added-ok"		=> " fue agregado/a exitosamente!.",
		"back" 			=> "Atr&aacute;s",
		"return" 		=> "Regresar a: ",
		"or" 			=> "o",
		"online" 		=> "En L&iacute;nea",
		"cant-loaded" 	=> "no se puede cargar.",
		"suggest-tag" 	=> "Sugerir Etiqueta",
		"suggest" 		=> "Sugerir",
		"select-file" 	=> "Selecciona un Archivo",
		"select-cat" 	=> "Selecciona una Categor&iacute;a para el Archivo",

		// F R O N T   E N D MODULE
		"view-all"		=> "Ver Todo",
		"view"		=> "Ver",
		"last-docs"		=> "&Uacute;ltimos Archivos",
		"last-cats" 	=> "&Uacute;ltimas Categor&iacute;as",
		"suscribe"		=> "Suscribirse",
		"search"		=> "Buscar",
		"clear" 		=> "Limpiar",
		"adm" 			=> "Administraci&oacute;n",	
		"stats" 		=> "Estad&iacute;sticas",
		"print" 		=> "Imprimir",
		"caps" 		=> "Permisos",
		
		
		"app-name" 		=> "Bejattos",
		"app-desc" 		=> "Sistema de Catalogaci&oacute;n de Productos",
		
		"categories"	=> "Categor&iacute;as",
		"category"		=> "Categor&iacute;a",
		"users"			=> "Usuarios",
		"user"			=> "Usuario",
		"clients"		=> "Clientes",
		"tags" 			=> "Etiquetas",
		"tag" 			=> "Etiqueta",
		"files"			=> "Archivos",
		"file"			=> "Archivo",
		
		"add-category"	=> "Agregar Categor&iacute;a",
		"add-user"		=> "Agregar Usuario",
		"add-client"	=> "Agregar Cliente",
		"create-account" => "Crear Cuenta",
		"webmessenger"	=> "Asignar Chat",
		"add-tag"		=> "Agreagr Etiqueta",
		"add-file"		=> "Agregar Archivo",
		
		"edit-category"	=> "Editar Categor&iacute;a",
		"edit-user"		=> "Editar Usuario",
		"edit-account"	=> "Editar Cuenta",
		"edit-client"	=> "Editar Cliente",
		"edit-tag"		=> "Editar Etiqueta",
		"edit-product"	=> "Editar Producto",
		"edit-product-min"	=> "Editar Producto Mini",
		"edit-order"	=> "Editar Pedido",
		"orders"	=> "Pedidos",
		"add-order"	=> "Agregar Pedido",
		
		"add"			=> "Agregar",
		"added"			=> "Agregado",
		"edit"			=> "Editar",
		"delete"		=> "Eliminar",
		"restore"		=> "Restaurar",
		
		"name"			=> "Nombre",
		"english"		=> "Ingl&eacute;s",
		"spanish"		=> "Espa&ntilde;ol",
		"manager"		=> "Administrador",
		
		"password"		=> "Contrase&ntilde;a",
		"logout"		=> "Cerrar Sesi&oacute;n",
		"id"			=> "ID",
		"since"			=> "Desde",
		"level"			=> "Nivel",
		"found"			=> "Encontrado(s)",
		"login"			=> "Iniciar Sesi&oacute;n",
		"sign-in"		=> "Iniciar Sesi&oacute;n",
		"welcome"		=> "Bienvenido",
		"download"		=> "Descargar",
		"dashboard"		=> "Tablero",
		
		"last-modified"	=> "&Uacute;ltima Actualizaci&oacute;n",
		"folder"		=> "Carpeta",
		"folders"		=> "Carpetas",
		"total"			=> "Total",
		"size-file"		=> "Tama&ntilde;o del Archivo",
		"size"			=> "Tama&ntilde;o",
		
		"copyright"		=> "Todos los Derechos Reservados.",
		"credits"		=> "Cr&eacute;ditos",
		
		
		// C A T E G O R Y MODULE
		
		"category-field" => "Campo Categor&iacute;a",
		"confirm-del"	=> "Estas seguro que deseas Eliminar",
		"invalid" 		=> "Invalido",
		"blockui-text"	=> "Por favor Espere...",
		"fields"		=> "Campos",
		"int"			=> "Entero",
		"text"			=> "Texto",
		"date"			=> "Fecha",
		"remove"		=> "Eliminar",		
		
		// U S E R S MODULE
		"e-mail"		=> "E-mail",
		"confirm"		=> "Confirmar",
		"new"			=> "Nuevo",
		"newa"			=> "Nueva",
		"retype"		=> "Reescribir",
		"unable"		=> "No es posible ejecutar esta acci&oacute;n",
		"theme"			=> "Tema",
		"preferences"	=> "Preferencias",
		"last-login"	=> "&Uacute;ltimo Inicio de Sesi&oacute;n",
		
		// F I L E MODULE
		"file-name"		=> "Nombre del Archivo",
		"explorer"		=> "Explorador",
		"select" 		=> "Seleccionar",
		"browse" 		=> "Navegar",
		"tag-field" 	=> "Campo Etiqueta",
		"desc"			=> "Descripci&oacute;n",
		"choose"		=> "Seleccionar",
		
		"trash"		=> "Papelera",		
		"none"		=> "Ninguno",
		"lang"		=> "Lenguaje"
		//"" => "",
	);
?>